// automatically generated by the FlatBuffers compiler, do not modify

package yangbot.cpp;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class CarCollisionInfo extends Table {
    public static CarCollisionInfo getRootAsCarCollisionInfo(ByteBuffer _bb) {
        return getRootAsCarCollisionInfo(_bb, new CarCollisionInfo());
    }

    public static CarCollisionInfo getRootAsCarCollisionInfo(ByteBuffer _bb, CarCollisionInfo obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static void startCarCollisionInfo(FlatBufferBuilder builder) {
        builder.startObject(2);
    }

    public static void addCarData(FlatBufferBuilder builder, int carDataOffset) {
        builder.addOffset(0, carDataOffset, 0);
    }

    public static void addImpact(FlatBufferBuilder builder, int impactOffset) {
        builder.addStruct(1, impactOffset, 0);
    }

    public static int endCarCollisionInfo(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public static void finishCarCollisionInfoBuffer(FlatBufferBuilder builder, int offset) {
        builder.finish(offset);
    }

    public static void finishSizePrefixedCarCollisionInfoBuffer(FlatBufferBuilder builder, int offset) {
        builder.finishSizePrefixed(offset);
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public CarCollisionInfo __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public FBSCarData carData() {
        return carData(new FBSCarData());
    }

    public FBSCarData carData(FBSCarData obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public FlatRay impact() {
        return impact(new FlatRay());
    }

    public FlatRay impact(FlatRay obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
    }
}

