// automatically generated by the FlatBuffers compiler, do not modify

package yangbot.cpp;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FlatCarCollisionInfo extends Table {
    public static FlatCarCollisionInfo getRootAsFlatCarCollisionInfo(ByteBuffer _bb) {
        return getRootAsFlatCarCollisionInfo(_bb, new FlatCarCollisionInfo());
    }

    public static FlatCarCollisionInfo getRootAsFlatCarCollisionInfo(ByteBuffer _bb, FlatCarCollisionInfo obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static void startFlatCarCollisionInfo(FlatBufferBuilder builder) {
        builder.startObject(2);
    }

    public static void addCarData(FlatBufferBuilder builder, int carDataOffset) {
        builder.addOffset(0, carDataOffset, 0);
    }

    public static void addImpact(FlatBufferBuilder builder, int impactOffset) {
        builder.addStruct(1, impactOffset, 0);
    }

    public static int endFlatCarCollisionInfo(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public FlatCarCollisionInfo __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public FlatCarData carData() {
        return carData(new FlatCarData());
    }

    public FlatCarData carData(FlatCarData obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public FlatRay impact() {
        return impact(new FlatRay());
    }

    public FlatRay impact(FlatRay obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
    }
}

