// automatically generated by the FlatBuffers compiler, do not modify

package yangbot.cpp;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FlatCarData extends Table {
    public static FlatCarData getRootAsFlatCarData(ByteBuffer _bb) {
        return getRootAsFlatCarData(_bb, new FlatCarData());
    }

    public static FlatCarData getRootAsFlatCarData(ByteBuffer _bb, FlatCarData obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static int createFlatCarData(FlatBufferBuilder builder,
                                        int physicsOffset,
                                        boolean onGround) {
        builder.startObject(2);
        FlatCarData.addPhysics(builder, physicsOffset);
        FlatCarData.addOnGround(builder, onGround);
        return FlatCarData.endFlatCarData(builder);
    }

    public static void startFlatCarData(FlatBufferBuilder builder) {
        builder.startObject(2);
    }

    public static void addPhysics(FlatBufferBuilder builder, int physicsOffset) {
        builder.addOffset(0, physicsOffset, 0);
    }

    public static void addOnGround(FlatBufferBuilder builder, boolean onGround) {
        builder.addBoolean(1, onGround, false);
    }

    public static int endFlatCarData(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public FlatCarData __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public FlatPhysics physics() {
        return physics(new FlatPhysics());
    }

    public FlatPhysics physics(FlatPhysics obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public boolean onGround() {
        int o = __offset(6);
        return o != 0 ? 0 != bb.get(o + bb_pos) : false;
    }
}

