// automatically generated by the FlatBuffers compiler, do not modify

package yangbot.cpp;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FlatNavigatorRequest extends Table {
    public static FlatNavigatorRequest getRootAsFlatNavigatorRequest(ByteBuffer _bb) {
        return getRootAsFlatNavigatorRequest(_bb, new FlatNavigatorRequest());
    }

    public static FlatNavigatorRequest getRootAsFlatNavigatorRequest(ByteBuffer _bb, FlatNavigatorRequest obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static void startFlatNavigatorRequest(FlatBufferBuilder builder) {
        builder.startObject(5);
    }

    public static void addStartPosition(FlatBufferBuilder builder, int startPositionOffset) {
        builder.addStruct(0, startPositionOffset, 0);
    }

    public static void addStartTangent(FlatBufferBuilder builder, int startTangentOffset) {
        builder.addStruct(1, startTangentOffset, 0);
    }

    public static void addEndPosition(FlatBufferBuilder builder, int endPositionOffset) {
        builder.addStruct(2, endPositionOffset, 0);
    }

    public static void addEndTangent(FlatBufferBuilder builder, int endTangentOffset) {
        builder.addStruct(3, endTangentOffset, 0);
    }

    public static void addEndTangentMultiplier(FlatBufferBuilder builder, float endTangentMultiplier) {
        builder.addFloat(4, endTangentMultiplier, 0.0f);
    }

    public static int endFlatNavigatorRequest(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public FlatNavigatorRequest __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public FlatVec3 startPosition() {
        return startPosition(new FlatVec3());
    }

    public FlatVec3 startPosition(FlatVec3 obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
    }

    public FlatVec3 startTangent() {
        return startTangent(new FlatVec3());
    }

    public FlatVec3 startTangent(FlatVec3 obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
    }

    public FlatVec3 endPosition() {
        return endPosition(new FlatVec3());
    }

    public FlatVec3 endPosition(FlatVec3 obj) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
    }

    public FlatVec3 endTangent() {
        return endTangent(new FlatVec3());
    }

    public FlatVec3 endTangent(FlatVec3 obj) {
        int o = __offset(10);
        return o != 0 ? obj.__assign(o + bb_pos, bb) : null;
    }

    public float endTangentMultiplier() {
        int o = __offset(12);
        return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
    }
}

