/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yangbot_cpp_YangBotCppInterop */

#ifndef _Included_yangbot_cpp_YangBotCppInterop
#define _Included_yangbot_cpp_YangBotCppInterop

struct ByteBuffer
{
	void* ptr;
	int size;
};

#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jfloatArray JNICALL Java_yangbot_cpp_YangBotCppInterop_getSurfaceCollision(JNIEnv*, jclass, jobject, jfloat);

	JNIEXPORT ByteBuffer __cdecl simulateBall(void* inputBall, int tickrate, float secs);

	JNIEXPORT jfloatArray JNICALL Java_yangbot_cpp_YangBotCppInterop_aerialML(JNIEnv*, jclass, jobject, jobject, jobject, jfloat);

	JNIEXPORT void JNICALL Java_yangbot_cpp_YangBotCppInterop_init(JNIEnv*, jclass, jbyte, jbyte);
	
	JNIEXPORT ByteBuffer __cdecl simulateCarCollision(void* inputCar);

	JNIEXPORT ByteBuffer __cdecl simulateSimpleCar(void* inputCar, float time);

	JNIEXPORT ByteBuffer __cdecl simulateCarBallCollision(void* inputCar, void* inputBall, float dt);

	JNIEXPORT ByteBuffer __cdecl findPath(void* pathRequest);
	
	JNIEXPORT void JNICALL Free( void*);

#ifdef __cplusplus
}
#endif
#endif
