/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yangbot_cpp_YangBotCppInterop */

#ifndef _Included_yangbot_cpp_YangBotCppInterop
#define _Included_yangbot_cpp_YangBotCppInterop
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     yangbot_cpp_YangBotCppInterop
	 * Method:    hello
	 * Signature: ()V
	 */
	JNIEXPORT jfloat JNICALL Java_yangbot_cpp_YangBotCppInterop_hello
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
