/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yangbot_cpp_YangBotCppInterop */

#ifndef _Included_yangbot_cpp_YangBotCppInterop
#define _Included_yangbot_cpp_YangBotCppInterop
#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jfloatArray JNICALL Java_yangbot_cpp_YangBotCppInterop_getSurfaceCollision(JNIEnv*, jclass, jobject, jfloat);

	JNIEXPORT jfloatArray JNICALL Java_yangbot_cpp_YangBotCppInterop_ballstep(JNIEnv*, jclass, jobject, jobject, jobject);

	JNIEXPORT void JNICALL Java_yangbot_cpp_YangBotCppInterop_init(JNIEnv*, jclass, jbyte, jbyte);
	
	JNIEXPORT jfloatArray JNICALL Java_yangbot_cpp_YangBotCppInterop_simulateCarCollision(JNIEnv* env, jclass thisObj, jobject pos, jobject vel);

#ifdef __cplusplus
}
#endif
#endif
